/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * SED.API
 * Backend do sistema de Entrevista de Desligamento - SED
 * OpenAPI spec version: v1.0.0.0
 */

export interface AlteracaoSenha {
  Codigo?: number;
  /** @nullable */
  Senha?: string | null;
  /** @nullable */
  NovaSenha?: string | null;
  /** @nullable */
  ConfirmaSenha?: string | null;
}
