/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * SED.API
 * Backend do sistema de Entrevista de Desligamento - SED
 * OpenAPI spec version: v1.0.0.0
 */

export interface DadosCabecalho {
  /** @nullable */
  Nome?: string | null;
  Idade?: number;
  /** @nullable */
  Unidade?: string | null;
  /** @nullable */
  Funcao?: string | null;
  /** @nullable */
  Setor?: string | null;
  /** @nullable */
  Admissao?: string | null;
  /** @nullable */
  Demissao?: string | null;
  /** @nullable */
  Encarregado?: string | null;
  /** @nullable */
  MotivoDeslig?: string | null;
  /** @nullable */
  DetMotivoDeslig?: string | null;
  /** @nullable */
  Consideracoes?: string | null;
  /** @nullable */
  Observacoes?: string | null;
  /** @nullable */
  DesistePedidoDesl?: string | null;
  /** @nullable */
  DataEntrevista?: string | null;
  /** @nullable */
  NomeUsuario?: string | null;
  /** @nullable */
  NomeGerente?: string | null;
}
