/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * SED.API
 * Backend do sistema de Entrevista de Desligamento - SED
 * OpenAPI spec version: v1.0.0.0
 */

export interface Entrevista {
  /** @nullable */
  Filial?: string | null;
  /** @nullable */
  Matricula?: string | null;
  /** @nullable */
  Nome?: string | null;
  /** @nullable */
  Idade?: string | null;
  /** @nullable */
  Data?: string | null;
  /** @nullable */
  CodigoFuncao?: string | null;
  /** @nullable */
  CodigoCentroCusto?: string | null;
  /** @nullable */
  DataAdmissao?: string | null;
  /** @nullable */
  DataDemissao?: string | null;
  CodigoUsuario?: number;
  CodigoMotDesligamento?: number;
  CodigoDetMotDesligamento?: number;
  /** @nullable */
  Consideracoes?: string | null;
  /** @nullable */
  Observacoes?: string | null;
  /** @nullable */
  DesistePedDeslig?: string | null;
  /** @nullable */
  Gerente?: string | null;
  /** @nullable */
  ListaEntrevista?: Entrevista[] | null;
}
