/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * SED.API
 * Backend do sistema de Entrevista de Desligamento - SED
 * OpenAPI spec version: v1.0.0.0
 */
import type { Entrevista } from './entrevista';
import type { EntrevistaEncarregadoModel } from './entrevistaEncarregadoModel';
import type { EntrevistaFatorDesligamentoModel } from './entrevistaFatorDesligamentoModel';
import type { EntrevistaAvaliacaoModel } from './entrevistaAvaliacaoModel';
import type { SegmentoModel } from './segmentoModel';
import type { CMotivoModel } from './cMotivoModel';
import type { RemuneracaoModel } from './remuneracaoModel';

export interface EntrevistaDesligamento {
  /** @nullable */
  ListaEntrevista?: Entrevista[] | null;
  /** @nullable */
  ListaEncarregado?: EntrevistaEncarregadoModel[] | null;
  /** @nullable */
  ListaFatorDesligamento?: EntrevistaFatorDesligamentoModel[] | null;
  /** @nullable */
  ListaAvaliacao?: EntrevistaAvaliacaoModel[] | null;
  /** @nullable */
  ListaSegmento?: SegmentoModel[] | null;
  /** @nullable */
  ListaMotivo?: CMotivoModel[] | null;
  /** @nullable */
  ListaRemuneracao?: RemuneracaoModel[] | null;
}
