/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * SED.API
 * Backend do sistema de Entrevista de Desligamento - SED
 * OpenAPI spec version: v1.0.0.0
 */

export interface EntrevistaBuscaModel {
  /** @nullable */
  Filial?: string | null;
  /** @nullable */
  Matricula?: string | null;
  /** @nullable */
  Nome?: string | null;
  /** @nullable */
  DescricaoFuncao?: string | null;
  /** @nullable */
  DescricaoCCusto?: string | null;
  /** @nullable */
  Motivo?: string | null;
  /** @nullable */
  DetMotivo?: string | null;
}
