/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * SED.API
 * Backend do sistema de Entrevista de Desligamento - SED
 * OpenAPI spec version: v1.0.0.0
 */

export type GetEntrevistaListaEntrevistasParams = {
dataDe?: string;
dataAte?: string;
tipoBusca?: string;
valor?: string;
fatorOperacional?: string;
fatorOperacionalResposta?: string;
avaliacaoGeral?: string;
avaliacaoGeralResposta?: string;
encarregado?: string;
filial?: string;
funcao?: string;
centroCusto?: string;
};
