/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * SED.API
 * Backend do sistema de Entrevista de Desligamento - SED
 * OpenAPI spec version: v1.0.0.0
 */

export interface Usuario {
  Codigo?: number;
  /** @nullable */
  Nome?: string | null;
  /** @nullable */
  User?: string | null;
  /** @nullable */
  Adm?: string | null;
  /** @nullable */
  Ativo?: string | null;
  /** @nullable */
  Senha?: string | null;
}
